# Generated by Django 2.2.2 on 2019-06-17 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='place',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='place.Place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('L', 'Light'), ('G', 'Generic on/off'), ('T', 'Tv remote control'), ('L', 'Light')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
