# Generated by Django 2.2.2 on 2019-06-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20190617_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
