# Generated by Django 2.2.2 on 2019-06-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='channel',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
