# Generated by Django 2.2.2 on 2019-10-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20191019_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('Light', 'Light'), ('Generic', 'Generic (on/off)'), ('Tv', 'Tv remote control')], default='Generic', max_length=20),
        ),
    ]
