# Generated by Django 2.2.2 on 2019-06-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_device_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='channel',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
