# Generated by Django 2.2.2 on 2019-06-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20190618_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mac',
            field=models.CharField(blank=True, max_length=17, unique=True),
        ),
    ]
