# Generated by Django 2.2.2 on 2019-06-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_device_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('Light', 'Light'), ('Generic', 'Generic (on/off)'), ('Tv', 'Tv remote control')], max_length=20),
        ),
    ]
