# Generated by Django 2.2.2 on 2019-06-30 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20190630_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='mac',
        ),
    ]
