# Generated by Django 2.2.2 on 2019-10-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('R', 'Room'), ('B', 'Bedroom'), ('K', 'Kitchen'), ('G', 'Garage')], max_length=1)),
            ],
        ),
    ]
