# Generated by Django 2.2.2 on 2019-06-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('R', 'Room'), ('B', 'Bedroom'), ('K', 'Kitchen'), ('G', 'Garage')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
